Repository MV-Clouds/Buildertek, pull requests merged in 2024-08, with the labels that each got.

#594 IBT-1814-BUIL-4297
  force-app/main/default/apex/OrderChecklistController.cls
  force-app/main/default/apex/OrderChecklistController.cls-meta.xml
  force-app/main/default/aura/ChooseBTChecklist/ChooseBTChecklist.cmp
  force-app/main/default/aura/ChooseBTChecklist/ChooseBTChecklistController.js
  force-app/main/default/classes/checkListQuestionsCtrl.cls
  force-app/main/default/lwc/newBudgetItemcmp/newBudgetItemcmp.css
  force-app/main/default/lwc/newBudgetItemcmp/newBudgetItemcmp.html
  force-app/main/default/lwc/newBudgetItemcmp/newBudgetItemcmp.js
  force-app/main/default/lwc/orderChecklistSection/orderChecklistSection.html
  force-app/main/default/lwc/orderChecklistSection/orderChecklistSection.js
  force-app/main/default/lwc/orderChecklistSection/orderChecklistSection.js-meta.xml
Labels: bug

#599 IBT-1817 BUIL-4300 question sorting and fixing checklist logo
  force-app/main/default/aura/ChecklistForm/ChecklistForm.cmp
  force-app/main/default/aura/ChecklistSettings/ChecklistSettings.cmp
  force-app/main/default/aura/ChecklistSettings/ChecklistSettingsController.js
  force-app/main/default/classes/ChooseBTChecklist.cls
  force-app/main/default/classes/checkListQuestionsCtrl.cls
Labels: bug, enhancement

#598 IBT-1808 BUIL-4292 Mass Update on Budget driven from fieldset
  force-app/main/default/aura/budgetMassUpdate/budgetMassUpdate.cmp
  force-app/main/default/aura/budgetMassUpdate/budgetMassUpdate.css
  force-app/main/default/aura/budgetMassUpdate/budgetMassUpdateController.js
  force-app/main/default/aura/budgetMassUpdate/budgetMassUpdateHelper.js
  force-app/main/default/classes/massUpdateBudgetItem.cls
  force-app/main/default/classes/massUpdateBudgetItem.cls-meta.xml
Labels: enhancement

#597 IBT-1807 BUIL-4291 Global Markup on Budget
  force-app/main/default/classes/BT_CreateBudgetOnQuoteAcceptance.cls
  force-app/main/default/classes/BudgetPage.cls
  force-app/main/default/lwc/newBudgetItemcmp/newBudgetItemcmp.js
  force-app/main/default/pages/BT_CreateBudgetConfiguration.page
Labels: enhancement

#601 BudgetContractCreateHelper changes
  force-app/main/default/classes/BudgetContractCreateHelper.cls
Labels: enhancement

#606 IBT-1834 query updated for ordering budget item according to sort id
  force-app/main/default/classes/BudgetPage.cls
Labels: bug

#603 IBT-1824 Added payment term on po from vendor
  force-app/main/default/classes/New_PO_ComponentController.cls
Labels: enhancement
