Repository MV-Clouds/Buildertek, pull requests merged in 2024-03, with the labels that each got.

#363 BT 1437 BUIL-3944 fixed vendor resources filter issue
  force-app/main/default/classes/bryntumGanttController.cls
  force-app/main/default/lwc/ganttCSVExportComponent/ganttCSVExportComponent.js
  force-app/main/default/lwc/gantt_component/gantt_component.js
Labels: bug

#362 Bt 1456 b UI l 3953
  force-app/main/default/aura/BT_createPOfromBOM/BT_createPOfromBOM.cmp-meta.xml
  force-app/main/default/aura/BT_createPOfromBOM/BT_createPOfromBOMController.js
  force-app/main/default/aura/BT_createPOfromBOM/BT_createPOfromBOMHelper.js
  force-app/main/default/aura/BT_createPOfromBOM/BT_createPOfromBOMRenderer.js
  force-app/main/default/classes/createPOfromBOM_controller.cls
Labels: enhancement

#365 BT-1452 BUIL-3949 update the condition to fix a issue
  force-app/main/default/classes/NewGanttChartTaskTriggerHandler.cls
Labels: bug

#366 BT-1463-BUIL-3957
  force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformation.auradoc
  force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformation.cmp
  force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformation.cmp-meta.xml
  force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformation.css
  force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformation.design
  force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformation.svg
  force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformationController.js
  force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformationHelper.js
  force-app/main/default/aura/PrintSalesInvoiceInformation/PrintSalesInvoiceInformationRenderer.js
  force-app/main/default/classes/PreviewBillingsController.cls
Labels: New Development

#369 Bt 1461 b UI l 3959
  force-app/main/default/aura/ImportMasterSchedule/ImportMasterSchedule.cmp
  force-app/main/default/classes/ImportMasterSchedules.cls
  force-app/main/default/classes/bryntumGanttController.cls
  force-app/main/default/lwc/gantt_component/gantt_component.js
  force-app/main/default/lwc/gantt_component/gantt_component.js-meta.xml
  force-app/main/default/lwc/gantt_component/gantt_componentHelper.js
Labels: enhancement

#371 BT-1466 Not Copying Resource
  force-app/main/default/lwc/gantt_component/gantt_component.js
  force-app/main/default/lwc/gantt_component/gantt_componentHelper.js
Labels: bug

#367 BT-1454-BUIL-3956
  force-app/main/default/aura/RequestInvoiceFromPO/RequestInvoiceFromPO.auradoc
  force-app/main/default/aura/RequestInvoiceFromPO/RequestInvoiceFromPO.cmp
  force-app/main/default/aura/RequestInvoiceFromPO/RequestInvoiceFromPO.cmp-meta.xml
  force-app/main/default/aura/RequestInvoiceFromPO/RequestInvoiceFromPO.css
  force-app/main/default/aura/RequestInvoiceFromPO/RequestInvoiceFromPO.design
  force-app/main/default/aura/RequestInvoiceFromPO/RequestInvoiceFromPO.svg
  force-app/main/default/aura/RequestInvoiceFromPO/RequestInvoiceFromPOController.js
  force-app/main/default/aura/RequestInvoiceFromPO/RequestInvoiceFromPOHelper.js
  force-app/main/default/aura/RequestInvoiceFromPO/RequestInvoiceFromPORenderer.js
  force-app/main/default/classes/RequestInvoiceFromPOController.cls
  force-app/main/default/classes/RequestInvoiceFromPOController.cls-meta.xml
  force-app/main/default/classes/RequestInvoicePageController.cls
  force-app/main/default/classes/RequestInvoicePageController.cls-meta.xml
  force-app/main/default/pages/RequestInvoicePage.page
  force-app/main/default/pages/RequestInvoicePage.page-meta.xml
  force-app/main/default/staticresources/RequestImageUploaderImg.png
  force-app/main/default/staticresources/RequestImageUploaderImg.resource-meta.xml
Labels: New Development

#368 BT-1464-BUIL-3962
  force-app/main/default/aura/AddProductsToPurchaseOrder/AddProductsToPurchaseOrder.cmp
  force-app/main/default/aura/AddProductsToPurchaseOrder/AddProductsToPurchaseOrderController.js
  force-app/main/default/aura/AddProductsToPurchaseOrder/AddProductsToPurchaseOrderHelper.js
  force-app/main/default/classes/AddProductsToPurchaseOrder.cls
Labels: enhancement

#372 BT-1466 solved the bug that Dhruv show me in the gantt chart
  force-app/main/default/lwc/gantt_component/gantt_component.js
  force-app/main/default/lwc/gantt_component/gantt_componentHelper.js
Labels: bug

#373 BT-1470-BUIL-3966
  force-app/main/default/classes/AccountPayableHelper.cls
  force-app/main/default/classes/AddBudgetLineItemOnPayableInvoice.cls
  force-app/main/default/classes/BudgetDAO.cls
Labels: enhancement

#374 BT-1471-BUIL-3969
  force-app/main/default/classes/RequestInvoiceFromPOController.cls
Labels: enhancement

#383 IBT-1450-BUIL-3973
  force-app/main/default/aura/BT_CreateQuoteFromOpportunity/BT_CreateQuoteFromOpportunity.cmp
  force-app/main/default/aura/BT_CreateQuoteFromOpportunity/BT_CreateQuoteFromOpportunityController.js
  force-app/main/default/classes/QuoteController.cls
Labels: enhancement

#382 IBT-1449-BUIL-3971
  force-app/main/default/aura/NewResourceScheduledashboard/NewResourceScheduledashboard.css
  force-app/main/default/aura/NewResourceScheduledashboard/NewResourceScheduledashboardController.js
  force-app/main/default/classes/NewResourceScheduleDashnoardCls.cls
  force-app/main/default/staticresources/ResourceScheduleDashboardMonthly.js
Labels: bug

#387 IBT-1461-BUIL-3987
  force-app/main/default/classes/CreateQuoteFromBOMController.cls
  force-app/main/default/classes/PurchaseOrderTriggerHandler.cls
  force-app/main/default/classes/createAllPOfromBOM_controller.cls
  force-app/main/default/classes/createPOfromBOM_controller.cls
  force-app/main/default/classes/createPOfromBOM_controller.cls-meta.xml
  force-app/main/default/classes/createSinglePOsController.cls
  force-app/main/default/pages/RequestInvoicePage.page
  force-app/main/default/triggers/PurchaseOrderTrigger.trigger
Labels: enhancement

#384 BUIL 3978 time sheets need a mass update button
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheet.auradoc
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheet.cmp
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheet.cmp-meta.xml
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheet.css
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheet.design
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheet.svg
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheetController.js
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheetHelper.js
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheetRenderer.js
  force-app/main/default/aura/BT_Redirect_MassUpdate_TimeSheet/BT_Redirect_MassUpdate_TimeSheet.auradoc
  force-app/main/default/aura/BT_Redirect_MassUpdate_TimeSheet/BT_Redirect_MassUpdate_TimeSheet.cmp
  force-app/main/default/aura/BT_Redirect_MassUpdate_TimeSheet/BT_Redirect_MassUpdate_TimeSheet.cmp-meta.xml
  force-app/main/default/aura/BT_Redirect_MassUpdate_TimeSheet/BT_Redirect_MassUpdate_TimeSheet.css
  force-app/main/default/aura/BT_Redirect_MassUpdate_TimeSheet/BT_Redirect_MassUpdate_TimeSheet.design
  force-app/main/default/aura/BT_Redirect_MassUpdate_TimeSheet/BT_Redirect_MassUpdate_TimeSheet.svg
  force-app/main/default/aura/BT_Redirect_MassUpdate_TimeSheet/BT_Redirect_MassUpdate_TimeSheetController.js
  force-app/main/default/aura/BT_Redirect_MassUpdate_TimeSheet/BT_Redirect_MassUpdate_TimeSheetHelper.js
  force-app/main/default/aura/BT_Redirect_MassUpdate_TimeSheet/BT_Redirect_MassUpdate_TimeSheetRenderer.js
  force-app/main/default/aura/BT_TimeSheetEntryMassUpdateApp/BT_TimeSheetEntryMassUpdateApp.app
  force-app/main/default/aura/BT_TimeSheetEntryMassUpdateApp/BT_TimeSheetEntryMassUpdateApp.app-meta.xml
  force-app/main/default/aura/BT_TimeSheetEntryMassUpdateApp/BT_TimeSheetEntryMassUpdateApp.auradoc
  force-app/main/default/aura/BT_TimeSheetEntryMassUpdateApp/BT_TimeSheetEntryMassUpdateApp.css
  force-app/main/default/aura/BT_TimeSheetEntryMassUpdateApp/BT_TimeSheetEntryMassUpdateApp.svg
  force-app/main/default/aura/BT_TimeSheetEntryMassUpdateApp/BT_TimeSheetEntryMassUpdateAppController.js
  force-app/main/default/aura/BT_TimeSheetEntryMassUpdateApp/BT_TimeSheetEntryMassUpdateAppHelper.js
  force-app/main/default/aura/BT_TimeSheetEntryMassUpdateApp/BT_TimeSheetEntryMassUpdateAppRenderer.js
  force-app/main/default/classes/BT_MassUpdate_TimeSheet.cls
  force-app/main/default/classes/BT_MassUpdate_TimeSheet.cls-meta.xml
  force-app/main/default/pages/TimeSheetEntryMassUpdate.page
  force-app/main/default/pages/TimeSheetEntryMassUpdate.page-meta.xml
Labels: New Development

#391 IBT-1466-BUIL-3995
  force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasic.cmp
  force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasicHelper.js
  force-app/main/default/aura/ImportMasterProjectTakeoff/ImportMasterProjectTakeoff.cmp
  force-app/main/default/classes/ImportMasterProjectTakeoff.cls
  force-app/main/default/classes/ImportTakeOffLinesBasic.cls
Labels: enhancement

#390 IBT-1458-BUIL-3993
  force-app/main/default/aura/BT_AddExistingBudget/BT_AddExistingBudget.cmp
  force-app/main/default/aura/BT_AddExistingBudget/BT_AddExistingBudgetHelper.js
  force-app/main/default/classes/AddExistingBudgetController.cls
  force-app/main/default/classes/AddExistingBudgetControllerTest.cls
  force-app/main/default/classes/createBudgetlineitemForTimeCard_AC.cls
Labels: enhancement

#388 IBT-1467-BUIL-3983
  force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp
  force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemCloneController.js
  force-app/main/default/classes/BudgetDAO.cls
Labels: enhancement

#396 Ibt 1475 b UI l 4001
  force-app/main/default/aura/OrderPOFromProject/OrderPOFromProject.cmp
  force-app/main/default/aura/OrderPOFromProject/OrderPOFromProjectController.js
  force-app/main/default/aura/OrderPOFromProject/OrderPOFromProjectHelper.js
Labels: bug, enhancement

#395 Added PO Id from parent component to fix the error
  force-app/main/default/aura/CreatePOLineFromPO/CreatePOLineFromPO.cmp
  force-app/main/default/aura/New_Purchase_Order_Item_Override/New_Purchase_Order_Item_Override.cmp
  force-app/main/default/aura/New_Purchase_Order_Item_Override/New_Purchase_Order_Item_OverrideHelper.js
Labels: bug

#393 IBT-1452 BUIL-3977 Added Category field in import csv
  force-app/main/default/classes/importScheduleLineController.cls
  force-app/main/default/lwc/importScheduleLine/importScheduleLine.html
  force-app/main/default/lwc/importScheduleLine/importScheduleLine.js
Labels: enhancement

#394 IBT-1468 BUIL-3991 Added space between btn
  force-app/main/default/aura/NewContractItem/NewContractItem.cmp
  force-app/main/default/aura/NewContractItem/NewContractItem.css
Labels: bug

#392 IBT - 1474 BUIL - 3998 Walkthrough line trigger
  force-app/main/default/classes/walkthroughlinetriggerhandler.cls
  force-app/main/default/classes/walkthroughlinetriggerhandler.cls-meta.xml
  force-app/main/default/classes/walkthroughlinetriggerhandlerTest.cls
  force-app/main/default/classes/walkthroughlinetriggerhandlerTest.cls-meta.xml
  force-app/main/default/triggers/walkthroughlinetrigger.trigger
  force-app/main/default/triggers/walkthroughlinetrigger.trigger-meta.xml
Labels: enhancement

#401 Ibt 1486 b UI l 3997
  force-app/main/default/aura/SingleProjectScheduleCalendar/SingleProjectScheduleCalendar.auradoc
  force-app/main/default/aura/SingleProjectScheduleCalendar/SingleProjectScheduleCalendar.cmp
  force-app/main/default/aura/SingleProjectScheduleCalendar/SingleProjectScheduleCalendar.cmp-meta.xml
  force-app/main/default/aura/SingleProjectScheduleCalendar/SingleProjectScheduleCalendar.css
  force-app/main/default/aura/SingleProjectScheduleCalendar/SingleProjectScheduleCalendar.design
  force-app/main/default/aura/SingleProjectScheduleCalendar/SingleProjectScheduleCalendar.svg
  force-app/main/default/aura/SingleProjectScheduleCalendar/SingleProjectScheduleCalendarController.js
  force-app/main/default/aura/SingleProjectScheduleCalendar/SingleProjectScheduleCalendarHelper.js
  force-app/main/default/aura/SingleProjectScheduleCalendar/SingleProjectScheduleCalendarRenderer.js
Labels: enhancement

#405 Bt 1475 b UI l 4019
  force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_Reviews.auradoc
  force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_Reviews.cmp
  force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_Reviews.cmp-meta.xml
  force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_Reviews.css
  force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_Reviews.design
  force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_Reviews.svg
  force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_ReviewsController.js
  force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_ReviewsHelper.js
  force-app/main/default/aura/BT_Import_Master_Reviews/BT_Import_Master_ReviewsRenderer.js
  force-app/main/default/classes/ImportMasterReviews.cls
  force-app/main/default/classes/ImportMasterReviews.cls-meta.xml
  force-app/main/default/classes/ImportMasterReviewsTest.cls
  force-app/main/default/classes/ImportMasterReviewsTest.cls-meta.xml
Labels: bug

#404 IBT-1484-BUIL-4006 fixed admin setting btn and required vendor field
  force-app/main/default/aura/New_PO_Component/New_PO_Component.cmp
  force-app/main/default/pages/BT_CreatePurchaseOrderConfiguration.page
Labels: bug
