Repository MV-Clouds/Buildertek, pull requests merged in 2024-02, with the labels that each got.

#318 BT 1366 BUIL 3855
  force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemCloneController.js
  force-app/main/default/classes/ConfirmationController.cls
  force-app/main/default/classes/QuoteDAO.cls
  force-app/main/default/classes/QuotelinesTableTemplate.cls
  force-app/main/default/classes/QuotelineswithGroupingNameController.cls
Labels: enhancement

#321 BT 1377 BUIL 3859 BUIL-3862 code added here
  force-app/main/default/classes/BudgetContractCreateHelper.cls
  force-app/main/default/classes/BudgetDAO.cls
Labels: enhancement

#323 BT 1361 BUIL-3848 Change Record Type
  force-app/main/default/aura/BT_NewChangeOrderOverride/BT_NewChangeOrderOverrideController.js
  force-app/main/default/aura/ChangeOrderRecordType/ChangeOrderRecordType.auradoc
  force-app/main/default/aura/ChangeOrderRecordType/ChangeOrderRecordType.cmp
  force-app/main/default/aura/ChangeOrderRecordType/ChangeOrderRecordType.cmp-meta.xml
  force-app/main/default/aura/ChangeOrderRecordType/ChangeOrderRecordType.css
  force-app/main/default/aura/ChangeOrderRecordType/ChangeOrderRecordType.design
  force-app/main/default/aura/ChangeOrderRecordType/ChangeOrderRecordType.svg
  force-app/main/default/aura/ChangeOrderRecordType/ChangeOrderRecordTypeController.js
  force-app/main/default/aura/ChangeOrderRecordType/ChangeOrderRecordTypeHelper.js
  force-app/main/default/aura/ChangeOrderRecordType/ChangeOrderRecordTypeRenderer.js
  force-app/main/default/classes/NewChangeOrderController.cls
Labels: enhancement

#320 BT-1374-BUIL-3864
  force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasic.cmp
  force-app/main/default/aura/BT_ImportTakeOffLinesCSVBasic/BT_ImportTakeOffLinesCSVBasicHelper.js
  force-app/main/default/classes/ImportTakeOffLinesBasic.cls
Labels: enhancement

#324 BT 1369 BUIL-3856 Added a field, fixed validation, fix the apex class
  force-app/main/default/aura/BT_ReceiveMaterialPOLines/BT_ReceiveMaterialPOLines.cmp
  force-app/main/default/aura/BT_ReceiveMaterialPOLines/BT_ReceiveMaterialPOLines.css
  force-app/main/default/aura/BT_ReceiveMaterialPOLines/BT_ReceiveMaterialPOLinesController.js
  force-app/main/default/classes/ReceiveMaterialPOLinesController.cls
Labels: enhancement

#326 BT 1381 BUIL-3869 Added vendor field while importing also updated error toast message
  force-app/main/default/classes/importScheduleLineController.cls
  force-app/main/default/lwc/gantt_component/gantt_component.css
  force-app/main/default/lwc/importScheduleLine/importScheduleLine.html
  force-app/main/default/lwc/importScheduleLine/importScheduleLine.js
Labels: enhancement

#325 BT-1384 BT_Email_service testclass
  force-app/main/default/classes/BT_Email_Services.cls
  force-app/main/default/classes/BT_Email_ServicesTest.cls
  force-app/main/default/classes/RFIresponsesHandler.cls
Labels: enhancement

#329 BT-1387-BUIL-3873
  force-app/main/default/classes/BT_CreateBOMfromTakeoffController.cls
Labels: enhancement

#332 BT-1398-BUIL-3885
  force-app/main/default/classes/ContractTriggerHandler.cls
  force-app/main/default/triggers/ContractTrigger.trigger
Labels: enhancement

#331 BT-1397-BUI-3884
  force-app/main/default/classes/TimeCardTriggerHandler.cls
Labels: enhancement

#335 BT 1390 BUIL 3874
  force-app/main/default/aura/BT_MassUpdateBillOfMaterialLines/BT_MassUpdateBillOfMaterialLines.auradoc
  force-app/main/default/aura/BT_MassUpdateBillOfMaterialLines/BT_MassUpdateBillOfMaterialLines.cmp
  force-app/main/default/aura/BT_MassUpdateBillOfMaterialLines/BT_MassUpdateBillOfMaterialLines.cmp-meta.xml
  force-app/main/default/aura/BT_MassUpdateBillOfMaterialLines/BT_MassUpdateBillOfMaterialLines.css
  force-app/main/default/aura/BT_MassUpdateBillOfMaterialLines/BT_MassUpdateBillOfMaterialLines.design
  force-app/main/default/aura/BT_MassUpdateBillOfMaterialLines/BT_MassUpdateBillOfMaterialLines.svg
  force-app/main/default/aura/BT_MassUpdateBillOfMaterialLines/BT_MassUpdateBillOfMaterialLinesController.js
  force-app/main/default/aura/BT_MassUpdateBillOfMaterialLines/BT_MassUpdateBillOfMaterialLinesHelper.js
  force-app/main/default/aura/BT_MassUpdateBillOfMaterialLines/BT_MassUpdateBillOfMaterialLinesRenderer.js
  force-app/main/default/classes/MassUpdateBOMLines.cls
  force-app/main/default/classes/MassUpdateBOMLines.cls-meta.xml
  force-app/main/default/classes/QuoteDAO.cls
Labels: enhancement

#334 BT-1388 BUIL-3879/80
  force-app/main/default/aura/BT_ReceiveMaterial/BT_ReceiveMaterial.cmp
  force-app/main/default/aura/BT_ReceiveMaterial/BT_ReceiveMaterialController.js
  force-app/main/default/aura/BT_ReceiveMaterialPOLines/BT_ReceiveMaterialPOLines.cmp
  force-app/main/default/aura/BT_ReceiveMaterialPOLines/BT_ReceiveMaterialPOLinesController.js
Labels: enhancement

#333 BT-1383 BUIL-3860
  force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemCloneHelper.js
Labels: enhancement

#336 BT-1399-BUIL-3889
  force-app/main/default/aura/BT_ImportSelectionSheet/BT_ImportSelectionSheet.cmp
  force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.css
  force-app/main/default/aura/ImportMasterProjectTakeoff/ImportMasterProjectTakeoff.cmp
  force-app/main/default/aura/ImportPurchaseOrderFromBudget/ImportPurchaseOrderFromBudgetController.js
  force-app/main/default/aura/Select_Quote_To_Import/Select_Quote_To_Import.cmp
  force-app/main/default/classes/BudgetDAO.cls
  force-app/main/default/classes/CO_From_Selection_Category.cls
  force-app/main/default/classes/ImportMasterProjectTakeoff.cls
  force-app/main/default/classes/ImportMasterSchedules.cls
  force-app/main/default/classes/ImportSelectionSheet.cls
  force-app/main/default/classes/ImportSubContractorForBudgetController.cls
  force-app/main/default/classes/ImportmasterBudgetClass.cls
  force-app/main/default/classes/PO_From_Selection_Sheet.cls
  force-app/main/default/classes/RFQDAO.cls
  force-app/main/default/classes/createCO_selectionType.cls
  force-app/main/default/classes/createRFQClass.cls
  force-app/main/default/classes/importTakeoff.cls
Labels: enhancement

#337 BT 1396 BUIL 3888 Email Scheduling
  force-app/main/default/classes/AccountExpirationEmailSender.cls
  force-app/main/default/classes/AccountExpirationEmailSender.cls-meta.xml
  force-app/main/default/classes/AccountTriggerHandler.cls
  force-app/main/default/classes/BT_AccountConfiguration.cls
  force-app/main/default/classes/BT_AccountConfiguration.cls-meta.xml
  force-app/main/default/classes/BT_AdminConfigurationController.cls
  force-app/main/default/pages/BT_AccountEmailConfiguration.page
  force-app/main/default/pages/BT_AccountEmailConfiguration.page-meta.xml
Labels: enhancement

#339 BT-1403 BUIL-3898 Left over sync vendor changes
  force-app/main/default/aura/syncVendors/syncVendors.cmp
  force-app/main/default/aura/syncVendors/syncVendors.cmp-meta.xml
  force-app/main/default/aura/syncVendors/syncVendorsController.js
  force-app/main/default/aura/syncVendors/syncVendorsHelper.js
  force-app/main/default/aura/syncVendors/syncVendorsRenderer.js
  force-app/main/default/classes/SyncVendorScheduleItem.cls
  force-app/main/default/classes/SyncVendorScheduleItem.cls-meta.xml
Labels: enhancement

#341 BT-1404 BUIL-3899 Updated the logic to directly display the template …
  force-app/main/default/aura/Preview_Billings/Preview_BillingsController.js
  force-app/main/default/aura/Preview_Payable/Preview_PayableController.js
  force-app/main/default/aura/Preview_PurchaseOrder/Preview_PurchaseOrderController.js
  force-app/main/default/aura/Preview_Quote/Preview_QuoteController.js
  force-app/main/default/aura/PurchaseOrderLineRelease/PurchaseOrderLineReleaseController.js
Labels: bug, enhancement

#342 BT-1405-BUIL-3896
  force-app/main/default/aura/New_InvoicePO_Component/New_InvoicePO_Component.cmp
  force-app/main/default/aura/SchedulePO/SchedulePO.cmp
  force-app/main/default/aura/SchedulePO/SchedulePO.css
  force-app/main/default/aura/SchedulePO/SchedulePOController.js
  force-app/main/default/aura/SchedulePO/SchedulePOHelper.js
  force-app/main/default/classes/SchedulePOController.cls
Labels: enhancement

#343 BT-1409 BUIL-3908 Fixed Schedule Issues
  force-app/main/default/classes/bryntumGanttController.cls
  force-app/main/default/lwc/gantt_component/gantt_component.js
  force-app/main/default/lwc/gantt_component/gantt_componentHelper.js
Labels: bug

#344 BT-1412-BUIL-3910
  force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp
  force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemCloneHelper.js
Labels: enhancement

#345 BT-1416-BUIL-3918
  force-app/main/default/aura/Import_Products_On_RfqLines/Import_Products_On_RfqLinesHelper.js
  force-app/main/default/classes/ImportMasterProjectTakeoffTest.cls
  force-app/main/default/classes/ImportMasterPunchLineTest.cls
  force-app/main/default/classes/ImportMasterQuotesTest.cls
  force-app/main/default/classes/ImportMasterSchedulesTest.cls
  force-app/main/default/classes/ImportmasterBudgetClassTest.cls
  force-app/main/default/classes/ImportmasterInspectionClassTest.cls
Labels: bug

#347 BT-1420-BUIL-3919
  force-app/main/default/aura/BT_ImportMasterToDo/BT_ImportMasterToDo.cmp
  force-app/main/default/aura/BT_ImportMasterToDo/BT_ImportMasterToDoController.js
  force-app/main/default/aura/BT_ImportMasterToDo/BT_ImportMasterToDoHelper.js
  force-app/main/default/classes/ImportMasterToDo.cls
Labels: enhancement

#351 BT-1427 BUIL-3913 Schedule changes
  force-app/main/default/lwc/gantt_component/gantt_component.css
  force-app/main/default/lwc/gantt_component/gantt_component.js
  force-app/main/default/lwc/gantt_component/gantt_componentHelper.js
  force-app/main/default/lwc/gantt_component/lib/BryntumGanttIcons.js
  force-app/main/default/lwc/gantt_component/lib/GanttToolbar.js
Labels: bug

#352 TestClass Issues
  force-app/main/default/classes/BT_FileSharingControllerTest.cls
  force-app/main/default/classes/ImportMasterToDoTest.cls
Labels: bug

#353 BT-1435-BUIL-3930
  force-app/main/default/lwc/gantt_component/gantt_component.js
  force-app/main/default/lwc/gantt_component/lib/GanttToolbar.js
Labels: enhancement

#359 BT-1438 BUIL-3942 Removed non working feature
  force-app/main/default/lwc/gantt_component/gantt_component.js
  force-app/main/default/lwc/gantt_component/gantt_componentHelper.js
  force-app/main/default/lwc/gantt_component/lib/GanttToolbar.js
Labels: bug

#360 BT-1452 BUIL-3949 Populate Actual start and end date based on completion %
  force-app/main/default/classes/NewGanttChartTaskTriggerHandler.cls
  force-app/main/default/triggers/ProjectTaskTrigger.trigger
Labels: enhancement

#355 BT-1440-BUIL-3946
  force-app/main/default/aura/BT_CreateWorkOrder/BT_CreateWorkOrder.auradoc
  force-app/main/default/aura/BT_CreateWorkOrder/BT_CreateWorkOrder.cmp
  force-app/main/default/aura/BT_CreateWorkOrder/BT_CreateWorkOrder.cmp-meta.xml
  force-app/main/default/aura/BT_CreateWorkOrder/BT_CreateWorkOrder.css
  force-app/main/default/aura/BT_CreateWorkOrder/BT_CreateWorkOrder.design
  force-app/main/default/aura/BT_CreateWorkOrder/BT_CreateWorkOrder.svg
  force-app/main/default/aura/BT_CreateWorkOrder/BT_CreateWorkOrderController.js
  force-app/main/default/aura/BT_CreateWorkOrder/BT_CreateWorkOrderHelper.js
  force-app/main/default/aura/BT_CreateWorkOrder/BT_CreateWorkOrderRenderer.js
  force-app/main/default/classes/createWorkOrderController.cls
  force-app/main/default/classes/createWorkOrderController.cls-meta.xml
Labels: enhancement

#356 BT-1447-BUIL-3945
  force-app/main/default/aura/PrintQuoteInformation/PrintQuoteInformation.cmp
  force-app/main/default/aura/PrintQuoteInformation/PrintQuoteInformationController.js
  force-app/main/default/aura/PrintQuoteInformation/PrintQuoteInformationHelper.js
Labels: enhancement

#357 BT-1451-BUIL-3948
  force-app/main/default/classes/BT_SendRFQEmailController.cls
Labels: bug

#361 BT-1453-BUIL-3950-PO-Tab
  force-app/main/default/aura/POPage/POPage.cmp
  force-app/main/default/aura/POPage/POPage.css
  force-app/main/default/aura/POPage/POPageController.js
  force-app/main/default/aura/POPage/POPageHelper.js
  force-app/main/default/classes/POPageController.cls
Labels: enhancement
