Repository MV-Clouds/Buildertek, pull requests merged in 2024-05, with the labels that each got.

#443 Add subject field in preview quote.
  force-app/main/default/aura/Preview_Quote/Preview_Quote.cmp
  force-app/main/default/aura/Preview_Quote/Preview_Quote.css
  force-app/main/default/aura/Preview_Quote/Preview_QuoteController.js
  force-app/main/default/aura/Preview_Quote/Preview_QuoteHelper.js
  force-app/main/default/classes/PreviewQuoteController.cls
  force-app/main/default/pages/RFQResponse.page-meta.xml
Labels: enhancement

#441 AFTER CREATING RFQ IT WILL REDIRECT ACCORDING TO REQUIREMENT
  force-app/main/default/aura/CreateRFQFromWalkThrough/CreateRFQFromWalkThroughHelper.js
  force-app/main/default/classes/CreateRFQFromWalkThroughController.cls
Labels: enhancement

#446 Add attachment functionality for preview email.
  force-app/main/default/aura/Preview_Quote/Preview_Quote.cmp
  force-app/main/default/aura/Preview_Quote/Preview_Quote.css
  force-app/main/default/aura/Preview_Quote/Preview_QuoteController.js
  force-app/main/default/aura/Preview_Quote/Preview_QuoteHelper.js
  force-app/main/default/classes/BT_SendEmailController.cls
  force-app/main/default/classes/PreviewQuoteController.cls
Labels: enhancement

#449 Ibt 1559 b UI l 4094
  force-app/main/default/classes/ConfigureScheduleFromSetting.cls
  force-app/main/default/classes/NewGanttChartTaskTriggerHandler.cls
  force-app/main/default/classes/bryntumGanttController.cls
  force-app/main/default/lwc/gantt_component/data/launch-saas.js
  force-app/main/default/lwc/gantt_component/gantt_component.js
  force-app/main/default/lwc/gantt_component/gantt_componentHelper.js
  force-app/main/default/pages/ConfigureScheduleFromSetting.page
Labels: enhancement

#455 IBT-1565 fixed too many soql error
  force-app/main/default/classes/AccountTriggerHandler.cls
Labels: bug

#454 IBT-1555 BUIL-4085 Delete Budget Item Issue
  force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp
  force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemCloneController.js
  force-app/main/default/classes/BudgetDAO.cls
Labels: bug

#453 IBT-1557 BUIL-4091 Mass Update For Time Sheet Entry
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheet.cmp
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheet.css
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheetController.js
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheetHelper.js
  force-app/main/default/classes/BT_MassUpdate_TimeSheet.cls
  force-app/main/default/classes/BT_MassUpdate_TimeSheet.cls-meta.xml
Labels: bug

#452 Ibt 1566 RFQ Item Trigger Error fixed
  force-app/main/default/aura/Import_Products_On_RfqLines/Import_Products_On_RfqLinesHelper.js
  force-app/main/default/classes/RFQItemTriggerHandler.cls
Labels: bug

#448 Add new functionality for sending email to related vendor on BT Schedule.
  force-app/main/default/aura/BT_EmailOnSchedule_Item/BT_EmailOnSchedule_Item.auradoc
  force-app/main/default/aura/BT_EmailOnSchedule_Item/BT_EmailOnSchedule_Item.cmp
  force-app/main/default/aura/BT_EmailOnSchedule_Item/BT_EmailOnSchedule_Item.cmp-meta.xml
  force-app/main/default/aura/BT_EmailOnSchedule_Item/BT_EmailOnSchedule_Item.css
  force-app/main/default/aura/BT_EmailOnSchedule_Item/BT_EmailOnSchedule_Item.design
  force-app/main/default/aura/BT_EmailOnSchedule_Item/BT_EmailOnSchedule_Item.svg
  force-app/main/default/aura/BT_EmailOnSchedule_Item/BT_EmailOnSchedule_ItemController.js
  force-app/main/default/aura/BT_EmailOnSchedule_Item/BT_EmailOnSchedule_ItemHelper.js
  force-app/main/default/aura/BT_EmailOnSchedule_Item/BT_EmailOnSchedule_ItemRenderer.js
  force-app/main/default/aura/Preview_Quote/Preview_Quote.cmp
  force-app/main/default/classes/BT_EmailOnSchedule_Item_Controller.cls
  force-app/main/default/classes/BT_EmailOnSchedule_Item_Controller.cls-meta.xml
  force-app/main/default/classes/BT_MultiSelectLookupController.cls
Labels: enhancement

#456 IBT-1559 fixed project duration issue bypassing the exclude Weekend l…
  force-app/main/default/lwc/gantt_component/gantt_component.js
  force-app/main/default/lwc/gantt_component/gantt_componentHelper.js
Labels: bug

#458 IBT-1573 fixed the phase selectin issue by setting grouping values in…
  force-app/main/default/aura/BT_MassAddBudgetItem/BT_MassAddBudgetItem.cmp
  force-app/main/default/aura/BT_MassAddBudgetItem/BT_MassAddBudgetItemController.js
  force-app/main/default/aura/BT_MassAddBudgetItem/BT_MassAddBudgetItemHelper.js
Labels: bug

#463 Ibt 1573 b UI l 4108
  force-app/main/default/aura/BT_LightningLookup/BT_LightningLookup.cmp
  force-app/main/default/aura/BT_LightningLookup/BT_LightningLookupController.js
  force-app/main/default/aura/BT_MassAddBudgetItem/BT_MassAddBudgetItem.cmp
Labels: bug

#461 IBT-1568 BUIL-4105 Create Single Sales Invoice Line Component
  force-app/main/default/aura/createSingleSalesInvoiceLine/createSingleSalesInvoiceLine.auradoc
  force-app/main/default/aura/createSingleSalesInvoiceLine/createSingleSalesInvoiceLine.cmp
  force-app/main/default/aura/createSingleSalesInvoiceLine/createSingleSalesInvoiceLine.cmp-meta.xml
  force-app/main/default/aura/createSingleSalesInvoiceLine/createSingleSalesInvoiceLine.css
  force-app/main/default/aura/createSingleSalesInvoiceLine/createSingleSalesInvoiceLine.design
  force-app/main/default/aura/createSingleSalesInvoiceLine/createSingleSalesInvoiceLine.svg
  force-app/main/default/aura/createSingleSalesInvoiceLine/createSingleSalesInvoiceLineController.js
  force-app/main/default/aura/createSingleSalesInvoiceLine/createSingleSalesInvoiceLineHelper.js
  force-app/main/default/aura/createSingleSalesInvoiceLine/createSingleSalesInvoiceLineRenderer.js
  force-app/main/default/classes/salesInvoiceController.cls
  force-app/main/default/classes/salesInvoiceController.cls-meta.xml
Labels: enhancement

#462 Ibt 1560 b UI l 4095 contractor invoice need to create a new button called send payment request
  force-app/main/default/aura/BT_SendPaymentRequest/BT_SendPaymentRequest.cmp
  force-app/main/default/aura/BT_SendPaymentRequest/BT_SendPaymentRequestController.js
  force-app/main/default/classes/SendPaymentRequestController.cls
Labels: enhancement

#464 IBT-1548-BUIL-4083-New-Project-Module
  force-app/main/default/classes/walkThroughController.cls
  force-app/main/default/classes/walkThroughController.cls-meta.xml
  force-app/main/default/lwc/newWalkThroughLineCmp/newWalkThroughLineCmp.css
  force-app/main/default/lwc/newWalkThroughLineCmp/newWalkThroughLineCmp.html
  force-app/main/default/lwc/newWalkThroughLineCmp/newWalkThroughLineCmp.js
  force-app/main/default/lwc/newWalkThroughLineCmp/newWalkThroughLineCmp.js-meta.xml
  force-app/main/default/lwc/newWalkThroughLineContainerCmp/newWalkThroughLineContainerCmp.css
  force-app/main/default/lwc/newWalkThroughLineContainerCmp/newWalkThroughLineContainerCmp.html
  force-app/main/default/lwc/newWalkThroughLineContainerCmp/newWalkThroughLineContainerCmp.js
  force-app/main/default/lwc/newWalkThroughLineContainerCmp/newWalkThroughLineContainerCmp.js-meta.xml
Labels: New Development

#469 Ibt 1604 b UI l 4134
  force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemCloneController.js
  force-app/main/default/classes/BudgetDAO.cls
  force-app/main/default/classes/QuoteDAO.cls
  force-app/main/default/triggers/QuoteItemTrigger.trigger
Labels: bug

#477 Ibt 1571 b UI l 4107
  force-app/main/default/aura/BT_SyncPOsOnSchedule/BT_SyncPOsOnSchedule.cmp
Labels: enhancement

#476 Ibt 1597 b UI l 4126
  force-app/main/default/classes/createVoidPOController.cls
Labels: enhancement

#474 Ibt 1588 b UI l 4113 time sheets mass update page needs work
  force-app/main/default/aura/BT_Mass_Update_TimeSheet/BT_Mass_Update_TimeSheetHelper.js
Labels: enhancement

#479 Ibt 1594 b UI l 4115
  force-app/main/default/classes/AccountPayableHelper.cls
  force-app/main/default/classes/PurchaseOrderDAO.cls
Labels: enhancement

#478 Ibt 1591 b UI l 4116
  force-app/main/default/aura/BT_CreateNewCashDisbursement/BT_CreateNewCashDisbursement.cmp
  force-app/main/default/aura/BT_CreateNewCashDisbursement/BT_CreateNewCashDisbursementController.js
  force-app/main/default/aura/BT_CreateNewCashDisbursement/BT_CreateNewCashDisbursementHelper.js
  force-app/main/default/classes/BT_NewCashDisbursementController.cls
  force-app/main/default/classes/CashDisbursementTriggerHandler.cls
Labels: enhancement

#473 IBT-1592-BUIL-4118 auto populate budget and budget line field on crea…
  force-app/main/default/classes/CreatePaymentForInvoiceAP.cls
Labels: enhancement

#472 Ibt 1569 b UI l 4104 quote adding new quote line need to pull in the notes field
  force-app/main/default/aura/Add_QuoteLine_In_Quote/Add_QuoteLine_In_Quote.cmp
  force-app/main/default/classes/QuoteDAO.cls
Labels: enhancement

#487 IBT-1615-BUIL-4136 assign project Id properly.
  force-app/main/default/classes/CreateRFQFromWalkThroughController.cls
Labels: documentation, enhancement

#486 Ibt 1627 b UI l 4145
  force-app/main/default/aura/Add_QuoteLine_In_Quote/Add_QuoteLine_In_Quote.cmp
  force-app/main/default/aura/Add_QuoteLine_In_Quote/Add_QuoteLine_In_Quote.css
  force-app/main/default/aura/Add_QuoteLine_In_Quote/Add_QuoteLine_In_QuoteHelper.js
  force-app/main/default/aura/Add_QuoteLine_from_Vendor/Add_QuoteLine_from_Vendor.cmp
  force-app/main/default/aura/Add_QuoteLine_from_Vendor/Add_QuoteLine_from_Vendor.css
  force-app/main/default/aura/Add_QuoteLine_from_Vendor/Add_QuoteLine_from_VendorHelper.js
  force-app/main/default/classes/CreateProjectfromQuoteAcceptanceonOpp.cls
  force-app/main/default/classes/QuoteDAO.cls
  force-app/main/default/pages/CreateProjectfromQuoteAcceptanceonOpp.page
  force-app/main/default/pages/CreateProjectfromQuoteAcceptanceonOpp.page-meta.xml
Labels: enhancement

#484 IBT-1628 updated css of quote single line component
  force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemClone.cmp
  force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemCloneController.js
  force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemCloneHelper.js
Labels: enhancement

#483 IBT- 1610 Handled Custom Validation Error on Purchase Order
  force-app/main/default/aura/New_PO_Component/New_PO_ComponentController.js
  force-app/main/default/classes/New_PO_ComponentController.cls
Labels: bug

#485 IBT-1611 Add PO
  force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp
  force-app/main/default/classes/BudgetDAO.cls
  force-app/main/default/classes/PurchaseOrderDAO.cls
  force-app/main/default/classes/PurchaseOrderItemTriggerHandler.cls
  force-app/main/default/classes/PurchaseOrderTriggerHandler.cls
  force-app/main/default/triggers/PurchaseOrderTrigger.trigger
Labels: bug

#489 IBT-1649 changed the soql query to sort it by vendor name and then co…
  force-app/main/default/aura/BT_RFQ_review_New_Clone/BT_RFQ_review_New_CloneController.js
  force-app/main/default/classes/RFQDAO.cls
Labels: enhancement

#491 IBT-1606 BUIL-4121 Contract Page fixed all open issues
  force-app/main/default/aura/BT_LightningLookup/BT_LightningLookup.cmp
  force-app/main/default/aura/BT_LightningLookup/BT_LightningLookupController.js
  force-app/main/default/aura/NewContractItem/NewContractItem.cmp
  force-app/main/default/aura/NewContractItem/NewContractItemController.js
  force-app/main/default/aura/NewContractItem/NewContractItemHelper.js
  force-app/main/default/classes/ContractDAO.cls
Labels: bug

#492 IBT-1613 fixed trigger issue
  force-app/main/default/classes/BillLineItemTriggerHandler.cls
Labels: bug

#493 Ibt 1633 Added Major desc field in grouping using cost code
  force-app/main/default/classes/QuotelineGroupingController.cls
  force-app/main/default/components/QuoteLineGroupingComponent.component
Labels: enhancement
