Repository MV-Clouds/Buildertek, pull requests merged in 2024-07, with the labels that each got.

#543 IBT 1709 BUIL-4198 Mass Update
  force-app/main/default/aura/Preview_Quote/Preview_QuoteHelper.js
  force-app/main/default/aura/quoteMassUpdateHelper/quoteMassUpdateHelper.auradoc
  force-app/main/default/aura/quoteMassUpdateHelper/quoteMassUpdateHelper.cmp
  force-app/main/default/aura/quoteMassUpdateHelper/quoteMassUpdateHelper.cmp-meta.xml
  force-app/main/default/aura/quoteMassUpdateHelper/quoteMassUpdateHelper.css
  force-app/main/default/aura/quoteMassUpdateHelper/quoteMassUpdateHelper.design
  force-app/main/default/aura/quoteMassUpdateHelper/quoteMassUpdateHelper.svg
  force-app/main/default/aura/quoteMassUpdateHelper/quoteMassUpdateHelperController.js
  force-app/main/default/aura/quoteMassUpdateHelper/quoteMassUpdateHelperHelper.js
  force-app/main/default/aura/quoteMassUpdateHelper/quoteMassUpdateHelperRenderer.js
  force-app/main/default/classes/QuotePage.cls
  force-app/main/default/lwc/massUpdateOnQuote/massUpdateOnQuote.css
  force-app/main/default/lwc/massUpdateOnQuote/massUpdateOnQuote.html
  force-app/main/default/lwc/massUpdateOnQuote/massUpdateOnQuote.js
  force-app/main/default/lwc/massUpdateOnQuote/massUpdateOnQuote.js-meta.xml
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.html
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.js
Labels: enhancement

#544 IBT-1721 Sorting quote item
  force-app/main/default/classes/QuotePage.cls
  force-app/main/default/classes/QuotePage.cls-meta.xml
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.html
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.js
Labels: enhancement

#548 IBT-1730 Added oppty field on correct configuration setting
  force-app/main/default/classes/BT_OpportunityConfiguration.cls
  force-app/main/default/classes/CreateProjectfromQuoteAcceptanceonOpp.cls
  force-app/main/default/classes/OpportunityTriggerHandler.cls
  force-app/main/default/pages/BT_CreateOpportunityConfiguration.page
  force-app/main/default/pages/CreateProjectfromQuoteAcceptanceonOpp.page
  force-app/main/default/pages/CreateProjectfromQuoteAcceptanceonOpp.page-meta.xml
Labels: bug

#547 Added proper styling to tables
  force-app/main/default/components/QuoteLineGroupingComponent.component
  force-app/main/default/components/QuotelineswithGroupingCmp.component
  force-app/main/default/components/QuotelineswithGroupingName.component
Labels: enhancement

#551 IBT-1737 BUIL-4223 Added Send Email functionality on Purchase Order
  force-app/main/default/aura/BT_EmailCO/BT_EmailCO.cmp
  force-app/main/default/aura/BT_EmailCO/BT_EmailCOHelper.js
  force-app/main/default/classes/BT_SendEmailController.cls
  force-app/main/default/lwc/massUpdateOnQuote/massUpdateOnQuote.css
  force-app/main/default/lwc/massUpdateOnQuote/massUpdateOnQuote.html
  force-app/main/default/lwc/massUpdateOnQuote/massUpdateOnQuote.js
Labels: enhancement

#552 IBT-1745-BUIL-4230
  force-app/main/default/classes/QuotelineswithGroupingNameController.cls
  force-app/main/default/classes/RFQDAO.cls
  force-app/main/default/components/QuotelineswithGroupingName.component
  force-app/main/default/lwc/addProductLwcCmp/addProductLwcCmp.js
  force-app/main/default/lwc/importRfqLwcCmp/importRfqLwcCmp.js
Labels: bug, enhancement

#553 IBT-1745 fixed the bug - only No Grouping record list index out of bound
  force-app/main/default/classes/QuotelineswithGroupingNameController.cls
Labels: bug

#554 IBT-1751 added Global Margin button logic and added logic for hide ma…
  force-app/main/default/classes/QuotePage.cls
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.css
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.html
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.js
Labels: enhancement

#555 Ibt 1755 b UI l 4240
  force-app/main/default/aura/BT_CreateQuoteFromBOM/BT_CreateQuoteFromBOM.cmp
  force-app/main/default/aura/BT_CreateQuoteFromBOM/BT_CreateQuoteFromBOM.cmp-meta.xml
  force-app/main/default/aura/BT_CreateQuoteFromBOM/BT_CreateQuoteFromBOMController.js
  force-app/main/default/aura/BT_CreateQuoteFromBOM/BT_CreateQuoteFromBOMHelper.js
  force-app/main/default/aura/BT_CreateQuoteFromBOM/BT_CreateQuoteFromBOMRenderer.js
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.css
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.html
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.js
Labels: enhancement

#561 IBT-1749 Added Grouping in Mass Update
  force-app/main/default/lwc/massUpdateOnQuote/massUpdateOnQuote.css
  force-app/main/default/lwc/massUpdateOnQuote/massUpdateOnQuote.html
  force-app/main/default/lwc/massUpdateOnQuote/massUpdateOnQuote.js
Labels: enhancement

#559 Ibt 1739 BUIL 4224 - Quote Page Component
  force-app/main/default/aura/quoteMassUpdateHelper/quoteMassUpdateHelperController.js
  force-app/main/default/lwc/importRfqLwcCmp/importRfqLwcCmp.js
  force-app/main/default/lwc/massUpdateOnQuote/massUpdateOnQuote.css
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.html
  force-app/main/default/pages/RFQResponse.page
Labels: enhancement

#556 IBT-1754-BUIL-4239
  force-app/main/default/classes/CreateProjectfromQuoteAcceptanceonOpp.cls
  force-app/main/default/classes/QuotelineswithGroupingNameController.cls
  force-app/main/default/components/QuotelineswithGroupingName.component
  force-app/main/default/pages/CreateProjectfromQuoteAcceptanceonOpp.page
Labels: enhancement

#557 IBT-1748 created new method with changed in query where all the quote…
  force-app/main/default/aura/BT_ImportFromQuote/BT_ImportFromQuoteController.js
  force-app/main/default/classes/ImportquoteClass.cls
Labels: enhancement

#567 IBT-1773-BUIL-4258
  force-app/main/default/aura/BT_CloneWalkThrough/BT_CloneWalkThrough.cmp
  force-app/main/default/aura/BT_CloneWalkThrough/BT_CloneWalkThrough.cmp-meta.xml
  force-app/main/default/aura/BT_CloneWalkThrough/BT_CloneWalkThroughController.js
  force-app/main/default/aura/BT_CloneWalkThrough/BT_CloneWalkThroughHelper.js
  force-app/main/default/classes/CloneWalkThroughController.cls
  force-app/main/default/classes/CloneWalkThroughController.cls-meta.xml
  force-app/main/default/classes/TestCloneWalkThroughController.cls
  force-app/main/default/classes/TestCloneWalkThroughController.cls-meta.xml
Labels: New Development

#568 IBT-1776 sort SOQL Query for quote grouping in QuotelineGroupingContr…
  force-app/main/default/classes/QuotelineGroupingController.cls
Labels: bug

#569 IBT-1778-BUIL-4263
  force-app/main/default/classes/BudgetContractCreateHelper.cls
  force-app/main/default/classes/CreateBudgetController.cls
Labels: enhancement

#574 IBT-1774 fixed css issue on WT
  force-app/main/default/lwc/newWalkThroughLineContainerCmp/newWalkThroughLineContainerCmp.css
  force-app/main/default/lwc/newWalkThroughLineContainerCmp/newWalkThroughLineContainerCmp.js
Labels: bug

#573 IBT-1779 Added new BOM field on takeoff
  force-app/main/default/classes/BT_CreateBOMfromTakeoffController.cls
Labels: enhancement

#570 IBT-1758 fixed test class issue
  force-app/main/default/classes/QuotelineswithGroupingNamecontrollerTest.cls
Labels: bug

#575 IBT-1780 Add Expense Functionality id completed
  force-app/main/default/classes/BudgetDAO.cls
  force-app/main/default/lwc/addExpenseFromBudget/addExpenseFromBudget.css
  force-app/main/default/lwc/addExpenseFromBudget/addExpenseFromBudget.html
  force-app/main/default/lwc/addExpenseFromBudget/addExpenseFromBudget.js
  force-app/main/default/lwc/addExpenseFromBudget/addExpenseFromBudget.js-meta.xml
  force-app/main/default/lwc/newBudgetItemcmp/newBudgetItemcmp.html
  force-app/main/default/lwc/newBudgetItemcmp/newBudgetItemcmp.js
Labels: enhancement

#580 IBT-4271 prevent sending email to manager by letting them knowing tha…
  force-app/main/default/classes/RFQAccepted.cls
  force-app/main/default/classes/RFQDAO.cls
Labels: enhancement

#591 IBT 1798 BUIL-4282 css fix on quote and budget
  force-app/main/default/lwc/newBudgetItemcmp/newBudgetItemcmp.css
  force-app/main/default/lwc/newBudgetItemcmp/newBudgetItemcmp.html
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.css
  force-app/main/default/lwc/newQuoteItemcmp/newQuoteItemcmp.html
Labels: enhancement

#590 IBT-1792 Added component to import PO line using csv
  force-app/main/default/aura/importPOLinesFromCSV/importPOLinesFromCSV.auradoc
  force-app/main/default/aura/importPOLinesFromCSV/importPOLinesFromCSV.cmp
  force-app/main/default/aura/importPOLinesFromCSV/importPOLinesFromCSV.cmp-meta.xml
  force-app/main/default/aura/importPOLinesFromCSV/importPOLinesFromCSV.css
  force-app/main/default/aura/importPOLinesFromCSV/importPOLinesFromCSV.design
  force-app/main/default/aura/importPOLinesFromCSV/importPOLinesFromCSV.svg
  force-app/main/default/aura/importPOLinesFromCSV/importPOLinesFromCSVController.js
  force-app/main/default/aura/importPOLinesFromCSV/importPOLinesFromCSVHelper.js
  force-app/main/default/aura/importPOLinesFromCSV/importPOLinesFromCSVRenderer.js
  force-app/main/default/classes/importPOLinesFromCsvController.cls
  force-app/main/default/classes/importPOLinesFromCsvController.cls-meta.xml
Labels: New Development

#585 IBT-1775 before optimization Mass Update Takeoff merge this ticket first
  force-app/main/default/aura/BT_MassUpdateTakeOffLines/BT_MassUpdateTakeOffLines.cmp
  force-app/main/default/aura/BT_MassUpdateTakeOffLines/BT_MassUpdateTakeOffLinesController.js
  force-app/main/default/aura/BT_MassUpdateTakeOffLines/BT_MassUpdateTakeOffLinesHelper.js
  force-app/main/default/classes/MassUpdateTakeOffLines.cls
Labels: enhancement

#592 IBT-1801 Takeoff fix 2
  force-app/main/default/aura/BT_MassUpdateTakeOffLines/BT_MassUpdateTakeOffLinesHelper.js
  force-app/main/default/classes/MassUpdateTakeOffLines.cls
Labels: bug

#593 IBT-1809 added unit cost field in the code
  force-app/main/default/classes/bryntumGanttController.cls
  force-app/main/default/lwc/gantt_component/gantt_component.js
  force-app/main/default/lwc/importRfqLwcCmp/importRfqLwcCmp.js
Labels: bug
