Repository MV-Clouds/Buildertek, pull requests merged in 2024-04, with the labels that each got.

#409 IBT-1490 Standard record type for PO
  force-app/main/default/classes/createAllPOfromBOM_controller.cls
  force-app/main/default/classes/createPOfromBOM_controller.cls
  force-app/main/default/classes/createSinglePOsController.cls
Labels: bug

#410 IBT-1483-BUIL-4011 New Requirement for Sync PO
  force-app/main/default/aura/BT_SyncPOsOnSchedule/BT_SyncPOsOnSchedule.cmp
  force-app/main/default/aura/BT_SyncPOsOnSchedule/BT_SyncPOsOnSchedule.css
  force-app/main/default/aura/BT_SyncPOsOnSchedule/BT_SyncPOsOnScheduleController.js
  force-app/main/default/aura/BT_SyncPOsOnSchedule/BT_SyncPOsOnScheduleHelper.js
  force-app/main/default/classes/BT_SyncPOsOnScheduleController.cls
  force-app/main/default/classes/ProjectTaskTriggerHandler.cls
  force-app/main/default/classes/PurchaseOrderTriggerHandler.cls
  force-app/main/default/triggers/ProjectTaskTrigger.trigger
Labels: enhancement

#412 IBT-1499-BUIL-4026 added inner group and add some css.
  force-app/main/default/aura/BT_createPOfromBOM/BT_createPOfromBOM.cmp
  force-app/main/default/aura/BT_createPOfromBOM/BT_createPOfromBOMHelper.js
  force-app/main/default/classes/createPOfromBOM_controller.cls
Labels: enhancement

#414 IBT-1497 BUIL-4024 Mass Update Vendor Review
  force-app/main/default/aura/BT360Map/BT360MapController.js
  force-app/main/default/aura/BT_MassUpdateWalkThroughLine/BT_MassUpdateWalkThroughLineHelper.js
  force-app/main/default/aura/MassUpdateVendorReview/MassUpdateVendorReview.auradoc
  force-app/main/default/aura/MassUpdateVendorReview/MassUpdateVendorReview.cmp
  force-app/main/default/aura/MassUpdateVendorReview/MassUpdateVendorReview.cmp-meta.xml
  force-app/main/default/aura/MassUpdateVendorReview/MassUpdateVendorReview.css
  force-app/main/default/aura/MassUpdateVendorReview/MassUpdateVendorReview.design
  force-app/main/default/aura/MassUpdateVendorReview/MassUpdateVendorReview.svg
  force-app/main/default/aura/MassUpdateVendorReview/MassUpdateVendorReviewController.js
  force-app/main/default/aura/MassUpdateVendorReview/MassUpdateVendorReviewHelper.js
  force-app/main/default/aura/MassUpdateVendorReview/MassUpdateVendorReviewRenderer.js
  force-app/main/default/classes/MassUpdateVendorReview.cls
  force-app/main/default/classes/MassUpdateVendorReview.cls-meta.xml
Labels: enhancement

#413 BT-1406 BUIL-3886 Schedule Resource
  force-app/main/default/aura/scheduleResourceComponent/scheduleResourceComponent.cmp
  force-app/main/default/aura/scheduleResourceComponent/scheduleResourceComponent.cmp-meta.xml
  force-app/main/default/aura/scheduleResourceComponent/scheduleResourceComponent.css
  force-app/main/default/aura/scheduleResourceComponent/scheduleResourceComponentHelper.js
  force-app/main/default/aura/scheduleResourceComponent/scheduleResourceComponentRenderer.js
  force-app/main/default/classes/scheduleResourceController.cls
  force-app/main/default/lwc/gantt_component/gantt_component.js
  force-app/main/default/lwc/gantt_component/gantt_componentHelper.js
  force-app/main/default/lwc/gantt_component/lib/GanttToolbar.js
  force-app/main/default/lwc/scheduleResources/scheduleResources.css
  force-app/main/default/lwc/scheduleResources/scheduleResources.html
  force-app/main/default/lwc/scheduleResources/scheduleResources.js
  force-app/main/default/lwc/scheduleResources/scheduleResources.js-meta.xml
  force-app/main/default/staticresources/ScheduleLWCCss.css
  force-app/main/default/staticresources/ScheduleLWCCss.resource-meta.xml
Labels: enhancement

#415 Ibt 1498 b UI l 4018
  force-app/main/default/aura/CloseQuickActionEvent/CloseQuickActionEvent.evt
  force-app/main/default/aura/CloseQuickActionEvent/CloseQuickActionEvent.evt-meta.xml
  force-app/main/default/aura/addImagesAura/addImagesAura.auradoc
  force-app/main/default/aura/addImagesAura/addImagesAura.cmp
  force-app/main/default/aura/addImagesAura/addImagesAura.cmp-meta.xml
  force-app/main/default/aura/addImagesAura/addImagesAura.css
  force-app/main/default/aura/addImagesAura/addImagesAura.design
  force-app/main/default/aura/addImagesAura/addImagesAura.svg
  force-app/main/default/aura/addImagesAura/addImagesAuraController.js
  force-app/main/default/aura/addImagesAura/addImagesAuraHelper.js
  force-app/main/default/aura/addImagesAura/addImagesAuraRenderer.js
  force-app/main/default/classes/fileUploadAndRenameController.cls
  force-app/main/default/classes/fileUploadAndRenameController.cls-meta.xml
  force-app/main/default/classes/fileUploadAndRenameControllerTest.cls
  force-app/main/default/classes/fileUploadAndRenameControllerTest.cls-meta.xml
  force-app/main/default/lwc/customImageDataTable/customImage.html
  force-app/main/default/lwc/customImageDataTable/customImageDataTable.html
  force-app/main/default/lwc/customImageDataTable/customImageDataTable.js
  force-app/main/default/lwc/customImageDataTable/customImageDataTable.js-meta.xml
  force-app/main/default/lwc/fileUploadAndRename/fileUploadAndRename.html
  force-app/main/default/lwc/fileUploadAndRename/fileUploadAndRename.js
  force-app/main/default/lwc/fileUploadAndRename/fileUploadAndRename.js-meta.xml
  force-app/main/default/staticresources/Jquery/jquery/js/jquery-ui-1.12.1.min.js
  force-app/main/default/staticresources/ResourceScheduleDashboardMonthly.js
Labels: enhancement, New Development

#417 IBT-1508-BUIL-4038
  force-app/main/default/aura/CreateRFQFromWalkThrough/CreateRFQFromWalkThrough.cmp
  force-app/main/default/aura/CreateRFQFromWalkThrough/CreateRFQFromWalkThroughController.js
  force-app/main/default/aura/CreateRFQFromWalkThrough/CreateRFQFromWalkThroughHelper.js
  force-app/main/default/classes/CreateRFQFromWalkThroughController.cls
Labels: enhancement

#418 IBT-1508 Brian said he wanted to add quantity field so added that
  force-app/main/default/classes/CreateRFQFromWalkThroughController.cls
Labels: enhancement

#420 IBT 1505 BUIL-4035 Create PO
  force-app/main/default/aura/BT_createPOfromBOM/BT_createPOfromBOM.cmp
  force-app/main/default/aura/BT_createPOfromBOM/BT_createPOfromBOMController.js
  force-app/main/default/aura/BT_createPOfromBOM/BT_createPOfromBOMHelper.js
Labels: bug

#419 IBT-1508 added buildertek__Quantity__c in soql
  force-app/main/default/classes/CreateRFQFromWalkThroughController.cls
Labels: enhancement

#426 IBT-1513 added condition to check for duplicate
  force-app/main/default/classes/createSinglePOsController.cls
Labels: bug

#429 IBT-1537 fixed the DAO Test Class and reduce timeout from 5 to 2 sec
  force-app/main/default/aura/BT_ManageBOMLines/BT_ManageBOMLinesController.js
  force-app/main/default/classes/ChangeOrderDAOTest.cls
  force-app/main/default/classes/ChangeOrderTriggerHandler.cls
  force-app/main/default/triggers/ChangeOrderTrigger.trigger
Labels: bug, enhancement

#434 Ibt 1537 b UI l 4062
  force-app/main/default/aura/BT_FieldSetMassUpdate/BT_FieldSetMassUpdate.cmp
  force-app/main/default/aura/BT_FieldSetMassUpdate/BT_FieldSetMassUpdateController.js
  force-app/main/default/aura/BT_LightningLookup/BT_LightningLookup.cmp
  force-app/main/default/aura/BT_LightningLookup/BT_LightningLookupController.js
  force-app/main/default/aura/BT_LightningLookupEvent/BT_LightningLookupEvent.evt
  force-app/main/default/aura/BT_LightningLookupResult/BT_LightningLookupResult.cmp
  force-app/main/default/aura/BT_LightningLookupResult/BT_LightningLookupResultController.js
  force-app/main/default/aura/BT_LookupEvent/BT_LookupEvent.evt
  force-app/main/default/aura/BT_LookupFields/BT_LookupFieldsController.js
  force-app/main/default/aura/BT_ManageBOMLines/BT_ManageBOMLines.cmp
  force-app/main/default/aura/BT_ManageBOMLines/BT_ManageBOMLinesController.js
  force-app/main/default/aura/BT_ManageBOMLines/BT_ManageBOMLinesHelper.js
  force-app/main/default/aura/BT_createPOfromBOM/BT_createPOfromBOM.cmp
  force-app/main/default/classes/FieldsetUtilityClass.cls
  force-app/main/default/classes/ManageBOMlinesController.cls
Labels: bug, enhancement
