Repository MV-Clouds/Buildertek, pull requests merged in 2024-06, with the labels that each got.

#497 ¯IBT-1661 added new row named Grand Total with all the column total
  force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemClone.cmp
  force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemCloneHelper.js
  force-app/main/default/classes/QuoteDAO.cls
Labels: enhancement

#499 IBT-1669 added code for bypassing the margin from the main quote line…
  force-app/main/default/classes/QuoteDAO.cls
Labels: bug

#500 IBT-1661 CSS issue fixed
  force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemClone.cmp
Labels: bug

#502 Ibt 1623 import po
  force-app/main/default/classes/BudgetItemTriggerHandler.cls
  force-app/main/default/classes/PurchaseOrderTriggerHandler.cls
  force-app/main/default/triggers/PurchaseOrderItemTrigger.trigger
  force-app/main/default/triggers/PurchaseOrderTrigger.trigger
Labels: enhancement

#505 IBT-1665-BUIL-4168
  force-app/main/default/aura/BT_approveAllPOLines/BT_approveAllPOLines.auradoc
  force-app/main/default/aura/BT_approveAllPOLines/BT_approveAllPOLines.cmp
  force-app/main/default/aura/BT_approveAllPOLines/BT_approveAllPOLines.cmp-meta.xml
  force-app/main/default/aura/BT_approveAllPOLines/BT_approveAllPOLines.css
  force-app/main/default/aura/BT_approveAllPOLines/BT_approveAllPOLines.design
  force-app/main/default/aura/BT_approveAllPOLines/BT_approveAllPOLines.svg
  force-app/main/default/aura/BT_approveAllPOLines/BT_approveAllPOLinesController.js
  force-app/main/default/aura/BT_approveAllPOLines/BT_approveAllPOLinesHelper.js
  force-app/main/default/aura/BT_approveAllPOLines/BT_approveAllPOLinesRenderer.js
  force-app/main/default/classes/approveallpolinesContrroller.cls
  force-app/main/default/classes/approveallpolinesContrroller.cls-meta.xml
Labels: enhancement

#504 Ibt 1664 b UI l 4167
  force-app/main/default/classes/PurchaseOrderTriggerHandler.cls
  force-app/main/default/classes/createVoidPOController.cls
Labels: enhancement

#501 IBT-1632-BUIL-4148 make table proper and professional
  force-app/main/default/aura/Import_Products_On_RfqLines/Import_Products_On_RfqLines.cmp
Labels: enhancement

#494 IBT-1660 BUIL-4165 Import Master Walk Through
  force-app/main/default/aura/BT_ImportMasterWalkThrough/BT_ImportMasterWalkThrough.auradoc
  force-app/main/default/aura/BT_ImportMasterWalkThrough/BT_ImportMasterWalkThrough.cmp
  force-app/main/default/aura/BT_ImportMasterWalkThrough/BT_ImportMasterWalkThrough.cmp-meta.xml
  force-app/main/default/aura/BT_ImportMasterWalkThrough/BT_ImportMasterWalkThrough.css
  force-app/main/default/aura/BT_ImportMasterWalkThrough/BT_ImportMasterWalkThrough.design
  force-app/main/default/aura/BT_ImportMasterWalkThrough/BT_ImportMasterWalkThrough.svg
  force-app/main/default/aura/BT_ImportMasterWalkThrough/BT_ImportMasterWalkThroughController.js
  force-app/main/default/aura/BT_ImportMasterWalkThrough/BT_ImportMasterWalkThroughHelper.js
  force-app/main/default/aura/BT_ImportMasterWalkThrough/BT_ImportMasterWalkThroughRenderer.js
  force-app/main/default/aura/ImportMasterWalkThrough/ImportMasterWalkThroughController.js
  force-app/main/default/classes/BT_ImportMasterWalkThroughController.cls
  force-app/main/default/classes/BT_ImportMasterWalkThroughController.cls-meta.xml
Labels: enhancement

#506 Ibt 1655 b UI l 4161
  force-app/main/default/aura/ChecklistForm/ChecklistForm.cmp
  force-app/main/default/aura/ChecklistForm/ChecklistFormController.js
  force-app/main/default/aura/ChecklistForm/ChecklistFormHelper.js
  force-app/main/default/classes/checkListQuestionsCtrl.cls
Labels: enhancement

#507 IBT-1675 new additional checklist requirement
  force-app/main/default/aura/ChecklistForm/ChecklistForm.cmp
  force-app/main/default/aura/ChooseBTChecklist/ChooseBTChecklist.cmp
  force-app/main/default/aura/ChooseBTChecklist/ChooseBTChecklist.css
  force-app/main/default/aura/ChooseBTChecklist/ChooseBTChecklistController.js
  force-app/main/default/aura/ChooseBTChecklist/ChooseBTChecklistHelper.js
  force-app/main/default/classes/ChooseBTChecklist.cls
Labels: enhancement

#513 IBT-1684 fixed the timezone issue on create schedule item cmp on PO
  force-app/main/default/aura/SchedulePO/SchedulePOController.js
  force-app/main/default/aura/SchedulePO/SchedulePOHelper.js
Labels: bug

#509 Ibt 1677 b UI l 4176
  force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemCloneController.js
  force-app/main/default/aura/NewQuoteItemClone/NewQuoteItemCloneHelper.js
  force-app/main/default/classes/QuoteDAO.cls
  force-app/main/default/classes/QuoteItemTriggerHandler.cls
Labels: enhancement

#510 IBT 1667 BUIL-4170 Import Master Walk Through
  force-app/main/default/aura/New_WalkThrough_Component/New_WalkThrough_Component.cmp
  force-app/main/default/aura/New_WalkThrough_Component/New_WalkThrough_ComponentController.js
  force-app/main/default/aura/New_WalkThrough_Component/New_WalkThrough_ComponentHelper.js
  force-app/main/default/classes/New_WalkThrough_Component.cls
Labels: enhancement, New Development

#516 Make cmp access global
  force-app/main/default/aura/SchedulePO/SchedulePO.cmp
Labels: bug

#523 Ibt 1689 b UI l 4159 sub task 1
  .forceignore
  .gitignore
  force-app/main/default/aura/BT_BudgetAddLines/BT_BudgetAddLines.cmp
  force-app/main/default/aura/ChooseBTChecklist/ChooseBTChecklist.cmp
  force-app/main/default/aura/ChooseBTChecklist/ChooseBTChecklistController.js
  force-app/main/default/classes/ChooseBTChecklist.cls
  force-app/main/default/lwc/createChecklistSectionAndSubsectionCmp/createChecklistSectionAndSubsectionCmp.html
  force-app/main/default/lwc/createChecklistSectionAndSubsectionCmp/createChecklistSectionAndSubsectionCmp.js
  force-app/main/default/lwc/createChecklistSectionAndSubsectionCmp/createChecklistSectionAndSubsectionCmp.js-meta.xml
  force-app/main/default/lwc/lookup/lookup.css
  force-app/main/default/lwc/lookup/lookup.html
  force-app/main/default/lwc/lookup/lookup.js
  force-app/main/default/lwc/lookup/lookup.js-meta.xml
Labels: enhancement

#514 IBT-1623 Child issue changes IBT-1668
  force-app/main/default/classes/PurchaseOrderTriggerHandler.cls
  force-app/main/default/triggers/PurchaseOrderTrigger.trigger
Labels: bug

#524 Ibt 1691 b UI l 4159 sub task 3
  force-app/main/default/aura/ChecklistForm/ChecklistForm.cmp
  force-app/main/default/aura/ChecklistForm/ChecklistFormController.js
  force-app/main/default/aura/ChecklistForm/ChecklistFormHelper.js
  force-app/main/default/classes/checkListQuestionsCtrl.cls
Labels: enhancement

#527 IBT-1653 Final Checklist changes
  force-app/main/default/aura/ChooseBTChecklist/ChooseBTChecklist.cmp
  force-app/main/default/aura/ChooseBTChecklist/ChooseBTChecklistController.js
  force-app/main/default/classes/ChooseBTChecklist.cls
  force-app/main/default/classes/ChooseBTChecklistTest.cls
  force-app/main/default/lwc/createChecklistSectionAndSubsectionCmp/createChecklistSectionAndSubsectionCmp.html
  force-app/main/default/lwc/createChecklistSectionAndSubsectionCmp/createChecklistSectionAndSubsectionCmp.js
  force-app/main/default/lwc/createChecklistSectionAndSubsectionCmp/createChecklistSectionAndSubsectionCmp.js-meta.xml
Labels: enhancement

#538 IBT-1681 Added type and contact field while submitting the checklist
  force-app/main/default/aura/checkListQuestions/checkListQuestionsController.js
Labels: enhancement

#537 IBT-1696 Hide Budget Buttons
  force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemClone.cmp
  force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemCloneController.js
  force-app/main/default/aura/BT_NewBudgetItemClone/BT_NewBudgetItemCloneHelper.js
  force-app/main/default/classes/BT_CreateBudgetOnQuoteAcceptance.cls
  force-app/main/default/classes/BudgetDAO.cls
  force-app/main/default/pages/BT_CreateBudgetConfiguration.page
Labels: enhancement

#535 IBT-1707 Added Close btn and correct date format
  force-app/main/default/aura/ChecklistForm/ChecklistForm.cmp
  force-app/main/default/aura/ChecklistForm/ChecklistFormHelper.js
Labels: bug

#536 IBT-1700 Linking poline to walk through line
  force-app/main/default/classes/CreatePOFromRFQ.cls
  force-app/main/default/classes/PurchaseOrderItemTriggerHandler.cls
  force-app/main/default/triggers/PurchaseOrderTrigger.trigger
Labels: enhancement
